examples/promptGeneration.ts
src/apis/generations.ts
src/index.ts

Adding the support for saved prompt generations.

feat: Add support for the saved prompt generations

---

.github/workflows/node-publish.yml

fix: ci workflow fix

---

.github/workflows/node-publish.yml
package-lock.json
package.json
src/version.ts

- Minor updates on the version

fix: Minor updates on the version

---

package-lock.json
package.json
src/version.ts

Feat/release 1.2.0

---

package-lock.json
package.json
src/version.ts

Feat/release 1.2.1

---

README.md

Add OpenAI SDK compliant blurb to readme

---

src/_types/generalTypes.ts
src/apis/createHeaders.ts
src/baseClient.ts
src/client.ts

**Title:** Debug support
- Support x-portkey-debug header 
client requirement
#50

TS Issue: debug header

---

package-lock.json

**Title:** Add missing package lock changes for openai dependency changes
- Update package-lock.json
Closes #57

chore: add package lock changes for openai dependency change

---

src/_types/generalTypes.ts
src/apis/createHeaders.ts
src/baseClient.ts
src/client.ts

**Title:** Openai specific headers 
- added support of header x-portkey-openai-project
- added support of header x-portkey-openai-organization
- added vendor specific headers as well (azure, vertex, aws)
#78

feat: openai-project openai-organization headers added

---

src/client.ts

**Title:** Initializer for apiKey and baseURL
- replaced override with declare 
Closes #84

fix: initializer for apiKey and baseURL

---

src/_types/generalTypes.ts
src/apis/chatCompletions.ts
src/baseClient.ts
src/client.ts

**Title:** Vertex Changes
- allow support for the header strictOpenAiCompliance
- Change the chatCompletion response type to support index signature
Closes: #97

Vertex Changes

---

package-lock.json
package.json
src/version.ts

1.4.0-rc.1

---

src/_types/generalTypes.ts
src/baseClient.ts
src/client.ts

**Title:** Anthropic Beta Header
- Passing anthropic beta as optional string in the constructor
Fixes: #108

AnthropicBeta header

---

src/baseClient.ts

**Title:** strictOpenAiCompliance
- setting default value of strictOpenAiCompliance as false
Closes: #149

strictOpenAiCompliance

---

src/apis/admin.ts

**Title:** User invite resend
- support for admin.users.invites.resend
Closes: #147

User invite resend

---

src/apis/batches.ts

**Title:** Batches Output
- Supporting batches.output
Closes: #181

Batches Output

---

package-lock.json
package.json
src/_types/sharedTypes.ts
src/apis/assistants.ts
src/apis/chatCompletions.ts
src/apis/index.ts
src/apis/realtime.ts
src/apis/threads.ts
src/apis/vectorStores.ts
src/beta/realtime/index.ts
src/beta/realtime/ws.ts
src/client.ts
src/index.ts

**Title:** Vendoring
- Matching OAI 4.85.3
- Support for chat completion CRUD
- Support for chat completion message
- Support for Realtime
- Change in metadata request type
Support all method as per OAI Node v4.85.3
Closes: #177

Version Upgrade

---

build

**Title:** Build Script Updated
- Updated build scirpt
Pointed out by a user
Fixes: #185 
cc: @VisargD

.ts Files in the dist folder 

---

src/baseClient.ts

**Title:**  Headers in Prompt Completions
- Introducing extraHeaders argument in RequestOptions
Suggested by user.
Closes: #195

 Headers in Prompt Completions

---

src/_types/generalTypes.ts
src/baseClient.ts
src/client.ts

**Title:** Fireworks Header
- Support for: `fireworksAccountId`
Closes: #205

Fireworks Header

---

src/apis/configs.ts

**Title:** Config Del: id and slug
- Accepting slug and id for now
- Added deprecation warning with it as well
Maintaining uniformity 
Closes: #210

Delete Config ID and SLUG

---

src/apis/collections.ts
src/apis/generations.ts
src/apis/index.ts
src/apis/labels.ts
src/client.ts
src/constants.ts

Prompts Endpoints

---

src/apis/apiKeys.ts

**Title:** Api Key Creation
- added expires_at 
- added kwargs support 
Issue reported by a user on Discord
Fixes: #216

FIX: API Key Creation

---

src/apis/audio.ts
src/getAudioDuration.ts

**Title:** File system for browser env
- Conditional import for fs
- Checking if browser env then ignore file duration check and return null.
Resolved compile error for browser env users
Fixes: #219

FS Module 

---

package-lock.json
package.json
src/apis/evals.ts
src/apis/fineTuning.ts
src/apis/index.ts
src/client.ts

**Title:** Vendoring update OAI 4.94.0
- Evals 
- Evals Runs 
- Evals Runs Output Items
- Finetuning Checkpoint Permissions
Closes: #212

Vendoring OAI 4.94.0

---

package-lock.json
package.json
src/apis/containers.ts
src/apis/evals.ts
src/apis/index.ts
src/apis/responses.ts
src/client.ts

**Title:** Vendoring Update
- OAI v4.104.0 
Closes: #233

OAI 4.104.0

---

package-lock.json

**Title:** NPM Dependencies fixed 
- 4 vulnerabilities (1 low, 2 moderate, 1 critical)
- simple `npm audit fix`
Fixes: #259

FIX: NPM Dependencies
