src/_types/portkeyConstructs.ts
src/index.ts

**Title:**  remove deprecated interfaces
- Remove these interface: LLMOptions, Constructs, ConversationInput as they are no longer valid
- To remove unnecessary code
- Closes #25

chore: remove deprecated interfaces

---

src/_types/generalTypes.ts
src/apis/createHeaders.ts
src/baseClient.ts
src/client.ts

**Title:** cacheForceRefresh and empty headers fix
- Add an isEmpty check before setting header values to avoid empty headers in request.
- Accept cacheForceRefresh as a parm
- To fix errors and support latest signature
- Fixes #33 
- Fixes #32

fix: cacheForceRefresh and empty headers fix

---

package.json

**Title:** OpenAI Version lock
- To support OpenAI upto a particular version
- beta.assistants.file .message.files etc support issue
#57

hotfix: openai version lock

---

src/apis/generations.ts

**Title:** Response type of Prompt Render
- The response type for the prompt render is fixed
- From generic to specific response type for this route
Reported as bug by user (https://discord.com/channels/1143393887742861333/1145181039648583811/1224288432411639869)
#52

Prompt Render Response

---

src/_types/generalTypes.ts
src/baseClient.ts
src/client.ts

**Title:** cacheNamespace header support
- Optional header key added cacheNamespace
**Motivation**
-  This is a secure way to prevent cache leakage.
#75

feat: added support for cacheNamespace header

---

src/apis/chatCompletions.ts

**Title:** response_format
- adding response_format as a body base in chat completion calls
Issue reported by user
Closes #77

response_format

---

.gitignore
src/apis/chatCompletions.ts

**Title:** Vercel response type for Chat completion stream
- Added the missing field for the chat completion response type
- function_call and tool_call were missing 
- fields added as optional fields 
- nested under chatCompletion -> choices -> delta 
Issue reported by a user on Discord: https://discord.com/channels/1143393887742861333/1143402158394454016/1242841759013404815
Closes #80

vercel response

---

jest.config.ts
tests/chat/anyscale.test.ts
tests/chat/openai.test.ts

- Chat Completions API tests for newer model on OpenAI
- Chat Completions API tests for newer models available on Anyscale
- Commented: Jest configuration to increase default timeout 20s
This adds more coverage in testing chat completions for more models.
Address #71

improvement: Tests for newer models of anyscale and openai

---

src/apis/assistants.ts
src/apis/files.ts
src/apis/images.ts
src/apis/models.ts
src/apis/threads.ts
src/utils.ts

**Title:** Client Initialization + Max retries
- setting maxRetries to 0
- single point to initializing client
maxRetries are 3 by default from openAI
Closes: #94

Client Initialization + Max retries

---

src/client.ts

I had an issue with the inferred type of the post method inside the Portkey class because of the overloads in the create method that it invokes, No major change, only added type for the response in the interface
Tested by using the post method
https://github.com/Portkey-AI/portkey-node-sdk/issues/105

fix: Type response in PortkeyClient because of issues with inferred type

---

src/baseClient.ts
src/streaming.ts

**Title:** Remove unused locals (to fix Typescript noUnusedLocals problem)
This PR removes some unused variables that cause TS to complain
For some reason I can't explain I'm getting these Typescript issues after having installed portkey. I have `compilerOptions.skipLibCheck = true` and `exclude: ["node_modules"]` in my tsconfig but it still happens. Even Claude Sonnet and GPT-4o are confused about why this is happening. Anyway, I figured I might as well contribute and improve the library rather than just applying a local patch
```
../node_modules/portkey-ai/dist/src/baseClient.ts:190:25 - error TS6133: 'path' is declared but its value is never read.
190         const { method, path, query, headers: headers = {}, body } = opts;
~~~~ …
```

Remove unused locals (to fix Typescript noUnusedLocals problem)

---

src/baseClient.ts

**Title:** Adding type `any`
- TS issue resolved by adding type `any`
- Since it returns Promise<any> hence we send it `as any`
Issue reported by User
Closes: #130

Spread Operator Issue: #130

---

src/client.ts
src/constants.ts
src/error.ts
src/utils.ts

**Title:** Making API Key optional is self hosted gateway
- Checking if it is not PORTKEY_BASE_URL then keep apiKey optional
- If apiKey not present, then set baseURL as localhost
Fixes #131

Making API Key optional is self hosted gateway

---

src/apis/threads.ts
src/baseClient.ts
src/utils.ts

**Title:**  Support for stream in Threads
- Adding stream in runs.create
- Adding stream in create_and_run
Closes: #141

feat: create and run stream support

---

src/apis/logsExport.ts
src/constants.ts

**Title:** Support for Insert Log
- Added create() to insert the log
Closes: #144

Insert Log

---

src/baseClient.ts
src/error.ts

**Title:** Error Details 
- Added error message and cause to the error
For better knowledge of the thrown error
Closes: #154

feat: added error message and cause

---

src/apis/chatCompletions.ts

**Title:** Request content type
- Content can be either string or array of any
Issue reported by User
Closes: #156

fix: request message content type

---

package-lock.json
package.json
src/apis/assistants.ts
src/apis/chatCompletions.ts
src/apis/completions.ts
src/apis/embeddings.ts
src/apis/files.ts
src/apis/images.ts
src/apis/threads.ts
src/apis/uploads.ts
src/apis/vectorStores.ts
src/baseClient.ts

**Title:** Updating to match OAI 4.77.0
- All the new request type, response time, methods
Closes: #151

feat: vendoring 4.77.0

---

src/_types/generalTypes.ts
src/apis/createHeaders.ts
src/baseClient.ts
src/client.ts

**Title:** forwardHeaders Logic
- Logic to check for forward headers array and not prefix x-portkey to those headers
- Provision to accept any extra values in the initialization 
Issue reported by user
Closes: #160

fix: forwardHeaders logic

---

src/apis/moderations.ts

**Title:** Updating the request body interface for moderations
- Allowing image_url in the updated request interface
Issue reported by user: https://discord.com/channels/1143393887742861333/1333351749712347158
Fixes: #170

Moderations Request Type

---

src/baseClient.ts
src/utils.ts

**Title:** retry request in case of failure
- max retry set as 1 
- retry portkey endpoints failure
- retry for openai endpoints failure
Handle the cloudflare error
Fixes: #165

Retry requests

---

src/_types/generalTypes.ts
src/baseClient.ts
src/client.ts
src/core.ts
src/utils.ts

**Title:** Getting fetch as per environment
- Made change on getting the fetch as per the SDK running environment 
- Passing Agent as per the environment 
Issue reported by user
Fixes: #168
**TBD**
Shall we add browser specific request headers as well?

Fix: SDK in browser

---

src/_types/generalTypes.ts
src/baseClient.ts
src/client.ts

**Title:** Headers needed for finetune
Support for: 
```
x-portkey-vertex-storage-bucket-name
x-portkey-provider-file-name
x-portkey-provider-model
x-portkey-aws-s3-bucket
x-portkey-aws-s3-object-key
x-portkey-aws-bedrock-model
```
Closes: #191

Headers for Finetune

---

src/apis/audio.ts
src/apis/batches.ts
src/apis/fineTuning.ts
src/apis/realtime.ts

**Title:** Support extra parameters in the body 
- Added provision for the `[key: string]: any;` in the request body interfaces
To support the all the providers request types
Closes: #189

Request Type

---

src/_types/chatCompletionTypes.ts
src/_types/index.ts
src/apis/chatCompletions.ts
src/index.ts

**Title:** Types: Chat Completion
- added types folder for chat completion
- export types in the index file
can be imported using: `import { types } from 'portkey-ai';` 
Closes: #198

Types: Chat Completion

---

src/apis/generations.ts

**Title:** Prompt Render Response Type
- Prompt Render messages content can be string or Array of any
User reported issue
Fixes: #257

FIX: Prompt Render Response Type

---

src/apis/audio.ts
src/client.ts
src/core.ts
src/getAudioDuration.ts

**Title:** FS Module Check
- FS Module Check
- Checking if the env is node or note
- Checking if env is browser then dangerouslyAllowBrowser is true or not
User reported issue
Fixes: #248

FS Module Check

---

src/utils.ts

**Title:** Headers check for FormData
- check for FormData, if present then remove content-type from default headers being set
Issue in using translation and transcription endpoints
Fixes: #271

Headers check for FormData
